export const DARES = [
"Go as long as you can without blinking",
"Spin around 10 times and try to walk straight.",
"Stand up and do jumping jacks until your next turn",
"Do 10 sit-ups",
"Show the other players five most recent photos in your camera roll",
"Do the splits, or go down as far as you can",
"Give your phone to another player to send a text message to a contact of their choice",
"Let the other players go through your phone for a minute",
"Sing the alphabet backwards",
"Try to sing a song with a mouthful of water",
"Sing a song chosen by the group",
"Play the next 3 rounds blindfolded",
"Make up a title for each players’ movie about their life",
"Let your friends pose you and stay like that until the next round",
"Make the ugliest face you can make",
"Empty your purse, backpack, or wallet and let everyone see what you have",
"Allow the person to your right to tickle you.",
"Do your best impression of a celebrity until someone guesses who it is",
"Sing a song in a completely different genre (e.g., opera version of a pop song).",
"Speak in an accent for the next three turns",
"Try to lick your elbow",
"Let someone blindfold you and try to identify three objects by touch",
"Act out a scene from a movie while others guess the title",
"Try to draw a portrait of someone in the group with your non-dominant hand",
"Do an interpretive dance to a song the group picks",
"Trade socks with the person to your right",
"Hold a plank position until your next turn",
"Act out a famous meme while others guess which one it is",
"Hold hands with the person to you left until next round",
"Speak only in questions until your next turn",
"Hold a staring contest with the person across from you",
"Do a slow-motion fight scene with an imaginary opponent",
"Serenade the person next to you.",
"Say the same sentence in five different emotions (angry, scared, flirty, etc.)",
"Do a trust fall into the group’s arms",
"Dance aggressively to a song of the group's choice",
"Let someone pose you like a mannequin—hold the position for 1 minute",
"High-five everyone in the room in the most dramatic way possible",
"Balance a spoon on your nose for 15 seconds",
"With your eyes closed, pick someone from your contact list and send them a text",
"Do your best impersonation of the person on your right.",
"Recite the alphabet while doing squats",
"Sketch a cat blindfolded",
"Perform a dramatic reading of a children's nursery rhyme like it's Shakespeare",
"Describe what the sky looks like without using the words blue or white",
"Sing the chorus of your favorite song",
"Do a full runway walk including poses, using household items as props",
"Make up a song about the host of the party",
"Do your best yoga pose and hold it for 30 seconds",
"Set a ridiculous alarm tone on your phone for tomorrow morning",
"From now until your next turn, every time someone talks, interrupt by saying, “that’s a lie”",
"Get down on one knee and propose to the person on your left",
"Until your next turn, when someone speaks, act as though you can’t hear what they are saying",
"Say nothing until your next turn",
"Wear your clothes backward for the duration of the game.",
"Hug the person to your right",
];
