export const TRUTHS = [
  "What’s the worst gift you’ve ever received?",
  "Who do you secretly admire?",
  "What is one thing you’ve never told anyone?",
  "Have you ever stolen something?",
  "Have you ever lied to your best friend?",
  "What’s the most embarrassing thing you’ve done in public?",
  "What’s the worst thing you’ve ever eaten?",
  "If you could be invisible for a day, what would you do?",
  "What’s one secret you’ve kept from your parents?",
  "Have you ever eavesdropped on a conversation?",
  "What’s the last thing you searched for online?",
  "Have you ever had a crush on a teacher?",
  "Have you ever been caught in a lie?",
  "If you could bring one celebrity back to life, who would it be?",
  "What’s your most embarrassing habit?",
  "Have you ever stalked someone on social media?",
  "What’s something you’ve done that you swore you never would?",
  "If you had to marry a cartoon character, who would it be?",
  "If you had to wear one outfit for the rest of your life, what would it be?",
  "Have you ever fallen asleep in a weird place?",
  "If you had to be a Disney princess, who would you be?",
  "If you had a theme song, what would it be?",
  "What’s the weirdest thing you’ve ever smelled and liked?",
  "Have you ever had an imaginary friend?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "Have you ever thought an object was alive?",
  "If you could live in any fictional world, where would you go?",
  "Have you ever worn clothes backward by accident?",
  "What’s one thing you wish your partner did differently?",
  "What’s the weirdest thing you’ve ever done when alone?",
  "If you could create a new body part, what would it do?",
  "Have you ever had a conversation with a pet?",
  "What’s the longest you’ve worn the same socks?",
  "What’s the best thing about being in a relationship?",
  "What’s the worst thing about being in a relationship?",
  "Have you ever snooped through your partner’s phone?",
  "Have you ever compared your relationship to someone else’s?",
  "Have you ever kept a secret from a partner?",
  "Do you cover your eyes during a scary part in a movie?",
  "What was the last thing you searched for on your phone web browser?",
  "Did your parents ever give you the “birds and the bees” talk?",
  "How much older of an individual would you enter a relationship with?",
  "Do you ever talk to yourself in the mirror?",
  "How would you rate your looks on a scale of 1 to 10?",
  "Would you rather live with no internet or no A/C or heating?",
  "What was your favorite childhood video game?",
  "If you were reborn, what decade would you want to be born in?",
  "Have you ever thought about cheating on your partner?",
  "Do you prefer a bath or a shower? Why?",
  "Do you sing in the shower?",
  "Have you ever kept a library book?",
  "What app on your phone do you waste the most time on?",
  "Have you ever pretended to be sick to get out of something?",
  "What is the single most painful experience of your life?",
  "Do you dance when you’re by yourself?",
  "Do you like hanging out with your parents?",
  "What’s the longest you’ve worn the same outfit for?",
  "What is your favorite type of ice cream?",
  "Where are you ticklish?",
];
